### ISSUE TITLE
Never push node modules in GitHub repo

### ISSUE THREAD

**Issue by narayann7** [anshumanbisoyi/Wiki-API#1]
## Never push node modules in GitHub repo
- node modules can be re-download as details of list of packages are there in package.json
- so create a .gitignore file in root folder where package.json, node modules is present 
-  and add node modules and env (for storing credentials i.e. mongo db URL, API keys)
* for example,  in .gitignore :
```
/node_modules
.env
```
so when ever you push code, your credentials and node modules will be not pushed in GitHub any platform 

## if you add now, it will not work
- delete  the node module, create .gitignore file then add above code
- so thing is .gitignore file will not get if it's already defined
- it will only get it if it is declared in gitignore file then u create the file and folder then it will remember to ignore

**Comment by anshumanbisoyi** [comment]
Added “node_modules” it in .gitignore file And pushed it. Missed “/“
instead of “/node_modules” I have written “node_modules”.

**Comment by narayann7** [comment]
i can see there is no gitignore file in the root. try it again, and tell. and in notion  use the code block to add code snippets

**Comment by anshumanbisoyi** [comment]
Issue solved.
